name: alarm_study
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  file_picker: ^8.0.0
  google_sign_in: ^7.2.0          # 구글 로그인
  kakao_flutter_sdk_user: ^1.9.7  # 카카오 로그인 (User API)
  flutter_secure_storage: ^9.2.2  # 로그인 토큰 안전하게 저장


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

