"""add required_count to alarm_sessions

Revision ID: 4a9d21360ab1
Revises: 660a221ac381
Create Date: 2026-08-01 16:12:34.812250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9d21360ab1'
down_revision: Union[str, Sequence[str], None] = '660a221ac381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_sessions', sa.Column('required_count', sa.SmallInteger(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm_sessions', 'required_count')
    # ### end Alembic commands ###
