"""initial schema

Revision ID: 660a221ac381
Revises: 
Create Date: 2026-07-29 12:48:36.475851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '660a221ac381'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=10), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('provider', 'provider_user_id', name=op.f('uq_users_provider'))
    )
    op.create_table('material_sets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_material_sets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_sets'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('alarms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('set_id', sa.BigInteger(), nullable=True),
    sa.Column('alarm_time', sa.Time(), nullable=False),
    sa.Column('repeat_days', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('sound', sa.String(length=50), server_default='default', nullable=False),
    sa.Column('volume', sa.SmallInteger(), server_default='80', nullable=False),
    sa.Column('is_vibration', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['material_sets.id'], name=op.f('fk_alarms_set_id_material_sets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alarms_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alarms'))
    )
    op.create_table('generation_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('set_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='pending', nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['material_sets.id'], name=op.f('fk_generation_jobs_set_id_material_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_jobs'))
    )
    op.create_index('uq_generation_jobs_set_id_active', 'generation_jobs', ['set_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'processing')"))
    op.create_table('study_materials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('set_id', sa.BigInteger(), nullable=False),
    sa.Column('is_main', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('upload_status', sa.String(length=12), server_default='pending', nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['material_sets.id'], name=op.f('fk_study_materials_set_id_material_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_materials')),
    sa.UniqueConstraint('s3_key', name=op.f('uq_study_materials_s3_key'))
    )
    op.create_index('uq_study_materials_set_id_main', 'study_materials', ['set_id'], unique=True, postgresql_where=sa.text('is_main = true'))
    op.create_table('weak_area_analyses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('set_id', sa.BigInteger(), nullable=False),
    sa.Column('weak_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['material_sets.id'], name=op.f('fk_weak_area_analyses_set_id_material_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weak_area_analyses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weak_area_analyses')),
    sa.UniqueConstraint('set_id', name=op.f('uq_weak_area_analyses_set_id'))
    )
    op.create_table('alarm_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('alarm_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismiss_method', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarms.id'], name=op.f('fk_alarm_sessions_alarm_id_alarms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alarm_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alarm_sessions'))
    )
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', sa.SmallInteger(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], name=op.f('fk_questions_material_id_study_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_table('wrong_answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', sa.SmallInteger(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.Column('wrong_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_wrong_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], name=op.f('fk_wrong_answers_material_id_study_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wrong_answers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wrong_answers'))
    )
    op.create_table('question_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=True),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('selected_answer', sa.SmallInteger(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), server_default='buffer', nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], name=op.f('fk_question_attempts_material_id_study_materials'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['alarm_sessions.id'], name=op.f('fk_question_attempts_session_id_alarm_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_attempts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_attempts')
    op.drop_table('wrong_answers')
    op.drop_table('questions')
    op.drop_table('alarm_sessions')
    op.drop_table('weak_area_analyses')
    op.drop_index('uq_study_materials_set_id_main', table_name='study_materials', postgresql_where=sa.text('is_main = true'))
    op.drop_table('study_materials')
    op.drop_index('uq_generation_jobs_set_id_active', table_name='generation_jobs', postgresql_where=sa.text("status IN ('pending', 'processing')"))
    op.drop_table('generation_jobs')
    op.drop_table('alarms')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('material_sets')
    op.drop_table('users')
    # ### end Alembic commands ###
